### ISSUE TITLE
error: getting status of '/run/user/1000/nix-prefetch/tmp.5UxKFqcQb3/pkgs

### ISSUE THREAD

**Issue by rmcgibbo** [msteen/nix-prefetch#10]
When using nix-prefetch (both master branch and the version in nixpkgs 20.03), I seem to be getting an error like this:

```
[mcgibbon@xps13:~/nixcfg/pkgs]$ nix-prefetch '(import ./. {}).pypyp'
error: getting status of '/run/user/1000/nix-prefetch/tmp.5UxKFqcQb3/pkgs': No such file or directory
```

It appears to come up only when I have overlays configured -- if I turn off my overlays the error magically disappears. Perhaps this is user error. If so, apologies for the noise.

**Comment by rmcgibbo** [comment]
I think I've identified the problem. The contents of my `overlays.nix` file uses a relative import (`import ./pkgs`), and it appears that the nix-prefetch is copying the overlays.nix without copying or symlinking the rest of the directory, so the import fails.

**Comment by msteen** [comment]
It is on the list of things to address, but it ideally requires thinking of a completely different workaround that I have yet to spend enough time to fully work out. I plan to do away with this copy trick, considering the issues it produces (yours, got one myself, and can think of others). However I did think of a probable solution which I just pushed. Let me know if it works for you.
