### ISSUE TITLE
Errors on MacOS (v0.3.1)

### ISSUE THREAD

**Issue by weberc2** [msteen/nix-prefetch#14]
Hello, I'm getting these errors when I try to run on MacOS with v0.3.1:

```bash
$ nix-prefetch hello
error: Could not determine the runtime directory (i.e. XDG_RUNTIME_DIR).

$ XDG_RUNTIME_DIR=$HOME/.cache nix-prefetch hello
error: Unsupported input type ''.

# Specifying an input type
$ XDG_RUNTIME_DIR=$HOME/.cache nix-prefetch hello --input nix
error: Unsupported input type 'nix'.
```

**Comment by msteen** [comment]
I am not familiar with MacOS. The first case should be fixed in the latest release. The other two errors are strange to me, as it concerns this line: `[[ $input_type =~ ^(|nix|json|shell)$ ]] || die "Unsupported input type '${input_type}'."`
As both values `''` or `'nix'` should and do match that regex on Linux.

Is MacOS using a different bash than Linux that does not support these regexes?

**Comment by siraben** [comment]
Still relevant to me

**Comment by kalekseev** [comment]
> Is MacOS using a different bash than Linux that does not support these regexes?

@msteen the regex `^(|nix|json|shell)$` is not posix compliant, | can't follow ( or another | or precede ) so it's not possible to match empty string https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_04_03:
`A <vertical-line> appearing first or last in an ERE, or immediately following a <vertical-line> or a <left-parenthesis>, or immediately preceding a <right-parenthesis>, produces undefined results.`

**Comment by antifuchs** [comment]
I'm hitting this on the 0.4.0 release as well - it feels weird that the `main.sh` script uses a bash from the nix store (`/nix/store/30njb8l701pwnm5ya749fh2cgyc2d70m-bash-4.4-p23/bin/bash`).

Anyway, I guess fixing those regexes might be the way forward for this issue.

**Comment by antifuchs** [comment]
With #24, I can use `nix-prefetch` on macOS again; would appreciate if other people could test!
