### ISSUE TITLE
Calculate cargoSha256?

### ISSUE THREAD

**Issue by colemickens** [msteen/nix-prefetch#6]
Hi, I'm using this tool to keep an overlay set of packages rev/sha256 to be up to date. However, one of my Rust packages has started updating their cargo multiple times a day, requiring manual intervention.

Could this tool learn how to handle `cargoSha256` cases as well?

**Comment by msteen** [comment]
I haven't tested it, but I am pretty sure this falls into the same category as the Go issue: https://github.com/msteen/nix-prefetch/issues/3#issuecomment-499293467

If that does not work for you, please let me know then I will take another look.

**Comment by colemickens** [comment]
```bash
pkgname="i3status-rust"
newcargoSha256="$(nix-prefetch '{ sha256 }: ${pkgname}.cargoDeps.overrideAttrs (_: { cargoSha256 = sha256; })')"
```

Thanks!
