### ISSUE TITLE
Support for sri/base64 hashes

### ISSUE THREAD

**Issue by Mic92** [msteen/nix-prefetch#7]
Currently nix-prefetch breaks with `nixFlakes` because it prints the new hashes.

https://github.com/NixOS/nix/issues/3786#issue-651736831

Notice this also is broken if the old nix is in PATH as the message is generated by nix-daemon.

**Comment by msteen** [comment]
This should have been addressed by the last commits based on your and @worldofpeace PRs. Thank you both and please let me know if it is failing somehow.

**Comment by msteen** [comment]
I have tried running the tests with `nixFlakes`, which is also what is reported when I run:
```
> nix --version
nix (Nix) 2.4pre20200721_ff314f1
```
However the hashes are still reported in the old format. Am I missing something important?

**Comment by msteen** [comment]
Guess it is nix-daemon, and I am only updating the client Nix. How would you implement a test that would work for both versions without full system rebuilds?

**Comment by Mic92** [comment]
> Guess it is nix-daemon, and I am only updating the client Nix. How would you implement a test that would work for both versions without full system rebuilds?

You can run nix in single-user mode with the `--store` parameter so it does not end up in the nix store.

**Comment by msteen** [comment]
For the sake of experimentation I just added `--store /tmp` to the calls to `nix eval`, but then I get:
```
error: --- BadStorePath ------------------------------------------------------------------------------- nix
path '/tmp/nix/store/zzw0vy3a4ds2x5744db1gkm66zzabfn3-nixos-20.03.git.6958957' is not in the Nix store
```
That path does actually exist though, it contains a checkout of my Nixpkgs as expected.

**Comment by Mic92** [comment]
Could be a bug in Nix itself. Personally I use github actions to test both versions: https://github.com/nix-community/nix-direnv/blob/master/.github/workflows/test.yml
